### ISSUE TITLE
HACS "support"

### ISSUE THREAD

**Issue by allanpersson** [Icescreamlol/Garmin_Connect#2]
First, thank you so much for the work with this integration 👏 

Second, it could be awesome if it could be part of HACS for easy install/update, and maybe more would/could help develop on it.
Here is some info about HACS: https://hacs.netlify.com/developer/integration/

And again, thank you so much for your effort and work on this integration 👍

**Comment by allanpersson** [comment]
https://github.com/hacs/default/pull/9

**Comment by allanpersson** [comment]
@Icescreamlol  As i'm not the code owner you will have to submit the PR, it's all available here https://github.com/hacs/default/pull/9

**Comment by Icescreamlol** [comment]
Better late than never, but if you could help me on how to do that, that would be great.

**Comment by allanpersson** [comment]
@Icescreamlol no problem, you just have to make a similar PR as the one i did here https://github.com/hacs/default/pull/9 and since you are the codeowner it should be enough :D

**Comment by allanpersson** [comment]
I see one official one is getting close(r) https://github.com/home-assistant/home-assistant/pull/30792
Maybe working together with that one is an idea? 🙏

**Comment by Icescreamlol** [comment]
To be fair... I think this guy is already further than I will every be.

**Comment by allanpersson** [comment]
I think you have done a really good job, and maybe your skills can be handy with the "official" one?! If you have the time and interest I'm sure you can be a good asset. I know from tapiriik fitness syncer garmin from time to time change their api, so more devolpers a better integration 😇🙏

Anyway, thanks for your work ❤️

**Comment by allanpersson** [comment]
https://rc.home-assistant.io/integrations/garmin_connect/ the official one is now live in 0.105.0b0 (Beta channel) :pray:
